project_id = "drvitjhhggcywuepyncx"

[functions.submit-lead]
verify_jwt = false

[functions.send-doctor-notification]
verify_jwt = false

[functions.send-patient-confirmation]
verify_jwt = false

[functions.update-leads-physician]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false